Models/TblInfoprenatal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace CentePreNat.Models
{
    public partial class TblInfoprenatal
    {
        [DisplayName("Historial Clinico")]
        public int PreHistorialClinico { get; set; }
        public int PreIdInfo { get; set; }
        [DisplayName("Numero de Embarazos")]
        public int? PreNumeroEmbarazo { get; set; }
        [DisplayName("Estado Emocional")]
        public string? PreEstadoEmocional { get; set; }
        [DisplayName("Salud Mental")]
        public string? PreSaludMental { get; set; }
        [DisplayName("Complicaciones")]
        public string? PreComplicaciones { get; set; }
        [DisplayName("Planificacion Familiar")]
        public string? PrePlanificacion { get; set; }
        [DisplayName("Aborto")]
        public string? PreAborto { get; set; }
        [DisplayName("Motivo")]
        public string? PreMotivo { get; set; }

        public virtual TblPaciente PreHistorialClinicoNavigation { get; set; } = null!;
    }
}

Controllers/TblInfoprenatalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CentePreNat.Models;

namespace CentePreNat.Controllers
{
    public class TblInfoprenatalsController : Controller
    {
        private readonly centeadminContext _context;

        public TblInfoprenatalsController(centeadminContext context)
        {
            _context = context;
        }

        // GET: TblInfoprenatals
        public async Task<IActionResult> Index( int? id)
        {
            var centeadminContext = _context.TblInfoprenatals.Include(t => t.PreHistorialClinicoNavigation)
                ;
            return View(await centeadminContext.ToListAsync());
        }


        // GET: TblInfoprenatals for id
        public IActionResult Index2(int? id)
        {
            var centeadminContext = from pre in _context.TblInfoprenatals
                                    where pre.PreHistorialClinico == id
                                    //join pac in _context.TblPacientes
                                    //  on pre.PreIdInfo equals id
                                    select new TblInfoprenatal
                                    {
                                        PreHistorialClinico = pre.PreHistorialClinico,
                                        PreIdInfo = pre.PreIdInfo,
                                        PreNumeroEmbarazo = pre.PreNumeroEmbarazo,
                                        PreEstadoEmocional = pre.PreEstadoEmocional,
                                        PreSaludMental = pre.PreSaludMental,
                                        PreComplicaciones = pre.PreComplicaciones,
                                        PrePlanificacion = pre.PrePlanificacion,
                                        PreAborto = pre.PreAborto,
                                        PreMotivo = pre.PreMotivo,
                                        PreHistorialClinicoNavigation = pre.PreHistorialClinicoNavigation
                                    };

            ViewData["PacId"]= id;
            return View(centeadminContext);
        }


        // GET: TblInfoprenatals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblInfoprenatals == null)
            {
                return NotFound();
            }

            var tblInfoprenatal = await _context.TblInfoprenatals
                .Include(t => t.PreHistorialClinicoNavigation)
                .FirstOrDefaultAsync(m => m.PreIdInfo == id);
            if (tblInfoprenatal == null)
            {
                return NotFound();
            }

            return View(tblInfoprenatal);
        }

        // GET: TblInfoprenatals/Create
        public IActionResult Create(int id)
        {
            //ViewData["PreHistorialClinico"] = new SelectList(_context.TblPacientes, "PacHistorialClinico", "PacHistorialClinico");
            ViewData["PreHistorialClinico"] = id;
           
            return View();
        }

        // POST: TblInfoprenatals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PreHistorialClinico,PreIdInfo,PreNumeroEmbarazo,PreEstadoEmocional,PreSaludMental,PreComplicaciones,PrePlanificacion,PreAborto,PreMotivo")] TblInfoprenatal tblInfoprenatal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblInfoprenatal);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PreHistorialClinico"] = new SelectList(_context.TblPacientes, "PacHistorialClinico", "PacHistorialClinico", tblInfoprenatal.PreHistorialClinico);
            return View(tblInfoprenatal);
        }

        // GET: TblInfoprenatals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblInfoprenatals == null)
            {
                return NotFound();
            }

            var tblInfoprenatal = await _context.TblInfoprenatals.FindAsync(id);
            if (tblInfoprenatal == null)
            {
                return NotFound();
            }
            ViewData["PreHistorialClinico"] = new SelectList(_context.TblPacientes, "PacHistorialClinico", "PacHistorialClinico", tblInfoprenatal.PreHistorialClinico);
            return View(tblInfoprenatal);
        }

        // POST: TblInfoprenatals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PreHistorialClinico,PreIdInfo,PreNumeroEmbarazo,PreEstadoEmocional,PreSaludMental,PreComplicaciones,PrePlanificacion,PreAborto,PreMotivo")] TblInfoprenatal tblInfoprenatal)
        {
            if (id != tblInfoprenatal.PreIdInfo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblInfoprenatal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblInfoprenatalExists(tblInfoprenatal.PreIdInfo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PreHistorialClinico"] = new SelectList(_context.TblPacientes, "PacHistorialClinico", "PacHistorialClinico", tblInfoprenatal.PreHistorialClinico);
            return View(tblInfoprenatal);
        }

        // GET: TblInfoprenatals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblInfoprenatals == null)
            {
                return NotFound();
            }

            var tblInfoprenatal = await _context.TblInfoprenatals
                .Include(t => t.PreHistorialClinicoNavigation)
                .FirstOrDefaultAsync(m => m.PreIdInfo == id);
            if (tblInfoprenatal == null)
            {
                return NotFound();
            }

            return View(tblInfoprenatal);
        }

        // POST: TblInfoprenatals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblInfoprenatals == null)
            {
                return Problem("Entity set 'centeadminContext.TblInfoprenatals'  is null.");
            }
            var tblInfoprenatal = await _context.TblInfoprenatals.FindAsync(id);
            if (tblInfoprenatal != null)
            {
                _context.TblInfoprenatals.Remove(tblInfoprenatal);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblInfoprenatalExists(int id)
        {
          return _context.TblInfoprenatals.Any(e => e.PreIdInfo == id);
        }

    }
}

Controllers/TblPacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CentePreNat.Models;
using Microsoft.EntityFrameworkCore.Internal;

namespace CentePreNat.Controllers
{
    public class TblPacientesController : Controller
    {
        private readonly centeadminContext _context;

        public TblPacientesController(centeadminContext context)
        {
            _context = context;
        }

        // GET: TblPacientes
        public async Task<IActionResult> Index()
        {
              return View(await _context.TblPacientes.ToListAsync());
        }

        // GET: TblPacientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblPacientes == null)
            {
                return NotFound();
            }

            var tblPaciente = await _context.TblPacientes
                .FirstOrDefaultAsync(m => m.PacHistorialClinico == id);
            if (tblPaciente == null)
            {
                return NotFound();
            }

            return View(tblPaciente);
        }

        // GET: TblPacientes/Create
        public IActionResult Create()
        {

            //var lastRecord = objContext.ResetPassword
            //               .Where(x
            //                     => x.Email == email
            //                     && x.Status == 0)
            //                 .OrderByDescending(x => x.Id)
            //                 .Take(1);
            return View();
        }

        // POST: TblPacientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PacHistorialClinico,PacApellidos,PacGenero,PacEdad,PacFnacimiento,PacDireccion,PacTelefono,PacInstruccion,PacInstitucion,PacFinformacion,PacEmail,PacFentregainforme")] TblPaciente tblPaciente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblPaciente);
               
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblPaciente);
        }

        // GET: TblPacientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblPacientes == null)
            {
                return NotFound();
            }

            var tblPaciente = await _context.TblPacientes.FindAsync(id);
            if (tblPaciente == null)
            {
                return NotFound();
            }
            return View(tblPaciente);
        }

        // POST: TblPacientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PacHistorialClinico,PacApellidos,PacGenero,PacEdad,PacFnacimiento,PacDireccion,PacTelefono,PacInstruccion,PacInstitucion,PacFinformacion,PacEmail,PacFentregainforme")] TblPaciente tblPaciente)
        {
            if (id != tblPaciente.PacHistorialClinico)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblPaciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblPacienteExists(tblPaciente.PacHistorialClinico))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblPaciente);
        }

        // GET: TblPacientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblPacientes == null)
            {
                return NotFound();
            }

            var tblPaciente = await _context.TblPacientes
                .FirstOrDefaultAsync(m => m.PacHistorialClinico == id);
            if (tblPaciente == null)
            {
                return NotFound();
            }

            return View(tblPaciente);
        }

        // POST: TblPacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblPacientes == null)
            {
                return Problem("Entity set 'centeadminContext.TblPacientes'  is null.");
            }
            var tblPaciente = await _context.TblPacientes.FindAsync(id);
            if (tblPaciente != null)
            {
                _context.TblPacientes.Remove(tblPaciente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblPacienteExists(int id)
        {
          return _context.TblPacientes.Any(e => e.PacHistorialClinico == id);
        }

        // GET: TblPacientes/Details/5
        public async Task<IActionResult> ProfilePaciente(int? id)
        {


            //var PacienteInfo = await _context.TblInfoprenatals
            //    .Join(_context.TblPacientes, info => info.PreHistorialClinico,
            //   pac => pac.PacHistorialClinico, (info, pac) => new { info, pac })
            //    .FirstOrDefaultAsync(x => x.info.PreIdInfo == id);

            //var PacienteInfo = await _context.TblPacientes
            //    .Join(_context.TblInfoprenatals, pac => pac.PacHistorialClinico,
            //    pre => pre.PreHistorialClinico, (pac,pre)=> new { pac,pre})
            //    .FirstOrDefaultAsync(x=> x.pac.PacHistorialClinico==id);

            //    .GroupJoin(_context.TblInfoprenatals, pac => pac.PacHistorialClinico,
            //    pre => pre.PreHistorialClinico, (pac, pre) => new { pac, pre })
            //    .FirstOrDefaultAsync(x => x.pac.PacHistorialClinico==id);

            //var PacienteInfo = await _context.TblPacientes
            //  .Join(_context.TblInfoprenatals, pac => pac.PacHistorialClinico, pre => pre.PreHistorialClinico, (pac, pre) => new { pac, pre })
            //   .ToListAsync();
            //var PacienteInfo = await _context.TblPacientes
            //    .Join(_context.TblInfoprenatals,pac => pac.PacHistorialClinico,pre => pre.PreHistorialClinico, (pac,pre)=> new { pac,pre} )
            //  .FirstOrDefaultAsync(m => m.pac.PacHistorialClinico == id);



            if (id == null || _context.TblPacientes == null)
            {
                return NotFound();
            }

            var tblPaciente = await _context.TblPacientes
               .FirstOrDefaultAsync(m => m.PacHistorialClinico == id)
                ;
            ViewData["Pacienteid"] = tblPaciente.PacHistorialClinico;
           

            if (tblPaciente == null)
            {
                return NotFound();
            }

            return View(tblPaciente);
        }
        public IActionResult GetIfoPrenat(int? id)
        {
            var centeadminContext = from pre in _context.TblInfoprenatals
                                    where pre.PreHistorialClinico == id
                                    //join pac in _context.TblPacientes
                                    //  on pre.PreIdInfo equals id
                                    select new TblInfoprenatal
                                    {
                                        PreHistorialClinico = pre.PreHistorialClinico,
                                        PreIdInfo = pre.PreIdInfo,
                                        PreNumeroEmbarazo = pre.PreNumeroEmbarazo,
                                        PreEstadoEmocional = pre.PreEstadoEmocional,
                                        PreSaludMental = pre.PreSaludMental,
                                        PreComplicaciones = pre.PreComplicaciones,
                                        PrePlanificacion = pre.PrePlanificacion,
                                        PreAborto = pre.PreAborto,
                                        PreMotivo = pre.PreMotivo,
                                        PreHistorialClinicoNavigation = pre.PreHistorialClinicoNavigation
                                    };

            ViewData["PacId"] = id;
            ViewData["prenat"] = centeadminContext;
            return View(centeadminContext);
        }

    }
}

Views/TblInfoprenatals/Create.cshtml
@model CentePreNat.Models.TblInfoprenatal

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TblInfoprenatal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PreHistorialClinico" class="control-label"></label>
                <input asp-for="PreHistorialClinico" value="@ViewData["PreHistorialClinico"]" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group">
                <label asp-for="PreIdInfo" class="control-label"></label>
                <input asp-for="PreIdInfo" class="form-control" />
                <span asp-validation-for="PreIdInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreNumeroEmbarazo" class="control-label"></label>
                <input asp-for="PreNumeroEmbarazo" class="form-control" />
                <span asp-validation-for="PreNumeroEmbarazo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreEstadoEmocional" class="control-label"></label>
                <input asp-for="PreEstadoEmocional" class="form-control" />
                <span asp-validation-for="PreEstadoEmocional" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreSaludMental" class="control-label"></label>
                <input asp-for="PreSaludMental" class="form-control" />
                <span asp-validation-for="PreSaludMental" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreComplicaciones" class="control-label"></label>
                <input asp-for="PreComplicaciones" class="form-control" />
                <span asp-validation-for="PreComplicaciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrePlanificacion" class="control-label"></label>
                <input asp-for="PrePlanificacion" class="form-control" />
                <span asp-validation-for="PrePlanificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreAborto" class="control-label"></label>
                <input asp-for="PreAborto" class="form-control" />
                <span asp-validation-for="PreAborto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreMotivo" class="control-label"></label>
                <input asp-for="PreMotivo" class="form-control" />
                <span asp-validation-for="PreMotivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TblInfoprenatals/Delete.cshtml
@model CentePreNat.Models.TblInfoprenatal

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblInfoprenatal</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreNumeroEmbarazo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreNumeroEmbarazo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreEstadoEmocional)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreEstadoEmocional)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreSaludMental)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreSaludMental)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreComplicaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreComplicaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrePlanificacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrePlanificacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreAborto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreAborto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreMotivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreMotivo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PreHistorialClinicoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PreHistorialClinicoNavigation.PacHistorialClinico)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PreIdInfo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TblInfoprenatals/Index2.cshtml
@model IEnumerable<CentePreNat.Models.TblInfoprenatal>

@{
    ViewData["Title"] = "Nuevo Informacion Prenatal";
    var idPac = ViewData["PacId"];

}


<div class="white-box ">
        <div class="row">
       @*    <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                   
                    <a asp-action="Create" asp-controller="TblInfoprenatals" class="btn btn-warning" asp-route-id="@idPac"><i class="fa fas fa-plus"></i> @ViewData["Title"]</a>
          
                    </div>
               
                </div><br>
            </div>*@

   
            <div id="verListPacientes">
             
                
            @*    <div class="row">
                    <div class="col-md-12">
                        <div class="alert-infoA">
                            Listado Informacion Prenatal
                            
                          </div>
                         
                    </div>
                </div>*@
                <br>
                <div class="row">
                    <div class="col-md-3 col-md-offset-9">
                        <form id="frmBusquedaPaciente">
                            <div class="input-group">
                                <input type="text" class="form-control" id="txtSearch" name="txtSearch" placeholder="Buscar Paciente" autocomplete="off" onkeydown="Mayusculas(this)">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
              
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive m-t-10">

                        <table class="table color-bordered-table info-bordered-table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreHistorialClinico)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreNumeroEmbarazo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreEstadoEmocional)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreSaludMental)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreComplicaciones)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PrePlanificacion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreAborto)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreMotivo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.PreHistorialClinicoNavigation)
                                    </th>
                                 
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                         <td>
                                            @Html.DisplayFor(modelItem => item.PreHistorialClinico)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreNumeroEmbarazo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreEstadoEmocional)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreSaludMental)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreComplicaciones)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PrePlanificacion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreAborto)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreMotivo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PreHistorialClinicoNavigation.PacHistorialClinico)
                                        </td>
                                                                            <td>
                                            @* <a asp-action="ProfilePaciente" asp-controller="TblPacientes" asp-route-id="@item.PacHistorialClinico">Ver Detalles</a>
                                           <button type="button" class="btn btn-info btn-outline btn-circle btn-lg m-r-5" data-toggle="tooltip" title="Editar" <i class="ti-pencil-alt"></i> </button>
                                            <a asp-action="Edit" asp-route-id="@item.PacHistorialClinico" >Edit</a> |
                                            <a asp-action="Details" asp-route-id="@item.PacHistorialClinico">Details</a> |
                                            <a asp-action="Delete" asp-route-id="@item.PacHistorialClinico">Delete</a>*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>